# Generated by Django 5.2.4 on 2025-07-09 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='Nombre del Producto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del producto', verbose_name='Fecha de Creación')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Precio del producto en pesos chilenos', max_digits=10, verbose_name='Valor')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa del producto', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
